### PR TITLE
Remove NIO headers added in #22

### PR DESCRIPTION
**Pull request by MrLotU**
#22 added double headers (metrics & NIO) to some files. This PR removes them

### CODE REVIEW

**Comment by MrLotU** [comment]
Yeah, but these files are not part of the NIO project, right?

**Comment by weissi** [comment]
> Yeah, but these files are not part of the NIO project, right?

They are copied from NIO, so they're now part of both the NIO and SwiftLog projects. That at least is my understanding.

**Comment by tomerd** [comment]
afaik under apache you should preserve the original license header on derived work. http://www.apache.org/legal/src-headers.html#3party

**Comment by Yasumoto** [comment]
Driveby (so feel free to ignore) but it [also mentions](http://www.apache.org/legal/src-headers.html#3party):

> 3. Do not add the standard Apache License header to the top of third-party source files.
> 4. Minor modifications/additions to third-party source files should typically be licensed under the same terms as the rest of the rest of the third-party source for convenience.

@davelester any thoughts? Just curious in general at this point.

**Comment by davelester** [comment]
+1 to @tomerd's comment. If the unmodified files are from another project, the original license headers would apply.

**Comment by Yasumoto** [comment]
Roger that, sounds like we should close this out then?

**Comment by ktoso** [comment]
Also agreed that that’s how copying files from other projects works under Apache.

Thanks a lot for the PR but seems we should close, thanks again @MrLotU :)

**Pull request closed without merging**
