### PR TITLE
Align supported Swift versions with rest of the ecosystem

### PR DESCRIPTION
**Pull request by FranzBusch**
# Motivation

Most of the server ecosystem follows the supported Swift versions from `swift-nio`. This means supporting the latest 3 Swift releases.

# Modification

This PR drops support for all Swift versions before 5.8.

# Result

This makes maintaining this repository easier and allows us to clean up some no longer needed stuff.

### CODE REVIEW

**Review by gjcairo — APPROVED** [review]

**Comment by yim-lee** [comment]
Deleted CI for Swift versions < 5.8.

Updated API breakage check to use Swift 5.10 (was using 5.1).

`scripts/soundness.sh` needs to be updated because `scripts/generate_linux_tests.rb` is removed.

```
=> Checking linux tests... ruby: No such file or directory -- /code/scripts/../scripts/generate_linux_tests.rb (LoadError)
1
Build step 'Execute shell' marked build as failure
```

@swift-server-bot test this please

**Comment by yim-lee** [comment]
Also updated branch rules to require Swift 5.8, 5.9 and 5.10 and remove previous Swift versions.

**Comment by ktoso** [comment]
We used to "try harder" for metrics and log, but I think it's fine to adopt the 3 versions rule. In reality this is what is actually going to work -- let's adopt this.

**Review by ktoso — APPROVED** [review]

**Comment by ktoso** [comment]
pull request validation (api breakage) gave a 404 hm

**Comment by ktoso** [comment]
This direction was discussed by the SSWG and we're aligning on the "3 versions back" rule

**Pull request merged**
