### PR TITLE
Import TestMetrics from swift-metrics-extras

### PR DESCRIPTION
**Pull request by ktoso**
After a long chain of "originally developed in" (swift distributed actors -> swift cluster membership -> swift metrics extras) finally moving the test metrics to where they should belong, the metrics repo!

This set of types allows for testing metrics.
The backend can be used in tests to bootstrap and then get metrics of the right label/dimensions and write assertions against them.

TODO:
- port the tests too (from actors, pretty sure we have some)

cc @fabianfett @tomerd

### CODE REVIEW

**Comment by ktoso** [comment]
Resolves https://github.com/apple/swift-metrics/issues/107

**Review by fabianfett — APPROVED** [review]
Looks good from my side. The only issue I can see is the potential naming conflict, since we now have `MetricsTestUtils` in `swift-metrics` and `swift-metrics-extras`. But since adopters need to declare which package an imported library is comming from this shouldn't be an issue, right?

**Comment by tomerd** [comment]
> The only issue I can see is the potential naming conflict, since we now have MetricsTestUtils in swift-metrics and swift-metrics-extras. But since adopters need to declare which package an imported library is coming from this shouldn't be an issue, right?

I actually think this is a problem.. at least until https://forums.swift.org/t/se-0339-module-aliasing-for-disambiguation/54730 is in place

**Comment by ktoso** [comment]
How about moving back to best name ever -- MetricsTestKit then? :-)

**Comment by fabianfett** [comment]
`MetricsTestKit` it is!

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
@swift-ci please smoke test

**Comment by ktoso** [comment]
@swift-server-bot test this please

**Comment by ktoso** [comment]
Merging since @fabianfett approved  👍

**Pull request merged**
